import {
  CalendarMonth,
  Email,
  Link,
  Person,
  Phone,
  Work,
  Money,
  Edit,
  PlayArrow,
  Pause,
  DeleteOutline,
  Menu,
  EditOutlined,
  ArchiveOutlined,
  MoneyOff,
  PaidOutlined,
  Add,
  NavigateBefore,
  NavigateNext,
  ArrowDropDown,
} from '@mui/icons-material';

import { IconsNamesMapType } from './types';

export const IconsMap: IconsNamesMapType = {
  calendarMonth: CalendarMonth,
  email: Email,
  link: Link,
  person: Person,
  phone: Phone,
  work: Work,
  money: Money,
  edit: Edit,
  playArrow: PlayArrow,
  pause: Pause,
  deleteOutline: DeleteOutline,
  menu: Menu,
  editOutlined: EditOutlined,
  archiveOutlined: ArchiveOutlined,
  moneyOff: MoneyOff,
  paidOutlined: PaidOutlined,
  add: Add,
  navigateBefore: NavigateBefore,
  navigateNext: NavigateNext,
  arrowDropDown: ArrowDropDown,
};
